### ISSUE TITLE
RegPack 4 has trouble with my 2016 JS1K entry

### ISSUE THREAD

**Issue by Qqwy** [Siorki/RegPack#36] opened 2016-02-07 10:23 UTC
My entry for JS1K 2016 is able to be compressed by passing it through the Closure Compiler and then RegPack to +- 1000 bytes. However, unpacking the output string returns improper code.

This is the Closure-Compiler-outputted code before going into RegPack (This code has been tested by placing it in the [2016 Shim](http://js1k.com/2016-elemental/shim.html),  it works without problems)

```
function d(e,g){0!=e&&(g=0);y=~~(p[p.length-1]/(s+1))+g;x=p[p.length-1]%(s+1)+e;if(0<=p.indexOf(y*(s+1)+x))p.indexOf(y*(s+1)+x)==p.length-2&&p.pop();else if(e&&l[Math.min(y*(s+1)+x,y*(s+1)+(x-e))]&1||g&&l[Math.min(y*(s+1)+x,(y-g)*(s+1)+x)]&2){if(y*(s+1)+x==(s+1)*(s+1))return 1;p.push(y*(s+1)+x)}}
function f(){c.fillStyle="#555";c.fillRect(-50,-50,1E5,1E5);c.strokeStyle="#000";c.lineWidth=15;c.lineCap="square";for(i=0;i<(s+1)*(s+1);i++)y=~~(i/(s+1)),x=i%(s+1),x-s+y==s&&(c.lineCap=c.lineJoin="round"),c.stroke(new Path2D("M"+30*x+w+30*y+(l[i]&1?"h 30":w)+"M"+30*x+w+30*y+(l[i]&2?"v 30":w)));o="";for(i=0;i<p.length;i++)y=~~(p[i]/(s+1)),x=p[i]%(s+1),o+=" L "+30*x+w+30*y;c.strokeStyle="#fff";c.stroke(new Path2D("M0 0 "+o));c.lineWidth=50;c.stroke(new Path2D("M0 0Z"))}
function u(e){s=3*Math.min(e,~~(a.height/100));l=[];for(i=0;i<(s+1)*(s+1);i++)y=~~(i/(s+1)),x=i%(s+1),l[i]=0,y%3||(l[i]|=1),x%3||(l[i]|=2),l[i]&1&&1==x%3&&(l[i]=.5<Math.random()?0:1),l[i]&2&&1==y%3&&(l[i]=.5<Math.random()?0:2),x==s&&(l[i]&=2),y==s&&(l[i]&=1),x-s+y==s&&(l[i]=1);p=[t=0];r=[0];for(v=[];0<r.length&&!(i=r.shift(),0>v.indexOf(i)&&(v.push(i),y=~~(i/(s+1)),x=i%(s+1),l[i]&1&&r.push(i+1),l[i]&2&&r.push(i+(s+1)),l[i-1]&1&&r.push(i-1),l[i-(s+1)]&2&&r.push(i-(s+1)),t=x-s+y==s)););f();t?b.onkeydown=
function(g){switch(g.keyCode%4){case 0:return d(0,-1)&&u(++e),f();case 1:return d(-1,0)&&u(++e),f();case 2:return d(0,1)&&u(++e),f();case 3:return d(1,0)&&u(++e),f()}}:setTimeout(function(){u(e)},0)}c.translate(0,a.height);c.scale(1,-1);c.translate(50,50);w=" ";u(1);
```

When RegPack'ed, I get the following output string:

```
for(_='c.stroke(new Path2D("MB;B0 0A),@(s+1)9/9@x=8c[c.77ta](Y;i++)Xcase W&&V);U)Vu(++e@f(UWK*9J7lI(eH-1G.lengthFp[pFG]]=7sS"#==[i 30":w)return for(0,){(yJ+xVl[min,l]%3||(|=a.height&x-s+y.pushy=~~(;i=0;i<i8i%9,   .indexOfsV(%3V(=.5<random()?0:"+30*x+w+30*y:d(Vr(ifunction9JX   i in c)c[0]+i[6]i; dH,g0!=eV(g=0U/9)+g;x=%9+e;if(0<=p))p)pF-2Vp.pop(Uelse ifHyJ+(x-e))]&1||g(y-g)J+x)]&2if9J)1;p)}} f(7fy"#555";7fc](-5-51E5,1E5U000";Id15;Ip"square"IpIi"round"@B+(1?"h+"M+(2?"v)Uo=""pFXp]8p]%9,o+=" L ;fff"A "+o)UId50AZ"))} uHs=3*minH,~~(/100)Ul=[]=y1@x2@1V1x1@2V1y2@x=2@y=1@=1Up=[t=0];r=[0];v=[];0<rFV!(i=r.shift(@0>v(i)V(v(i@ 1+1@2+9@lG]&1G@l-9]&2-9@t=s)UUf(Ut?b.onkeydown=(gswitch(g.keyCode%4W0GK1G,0K21K31,0)Vu(++e@f()}}:setTimeout((uH)},0)}YUc.scale(1,GUY550Uw=" ";u(1U';g=/[-F-KU-Y7-9@-B]/.exec(_);)with(_.split(g))_=join(shift());with(Math)eval(_)
```

When placing this in the shim, I get the following error:
`Uncaught ReferenceError: Invalid left-hand side in assignment`

By calling `console.log(_)` before the `with(Math)eval(_)` statement, I obtain the following code:

```
for(i in c)c[i[0]+i[6]]=i;function d(e,g){0!=e&&(g=0);y=~~(p[p.length-1]/(s+1))+g;x=p[p.length-1]%(s+1)+e;if(0<=py=~~(i/(s+1)),x=i%(s+1), .indexOf(y*(s+1)+x))py=~~(i/(s+1)),x=i%(s+1), .indexOf(y*(s+1)+x)==p.length-2&&p.pop();else if(e&&l[min(y*(s+1)+x,y*(s+1)+(x-e))]&1||g&&l[min(y*(s+1)+x,(y-g)*(s+1)+x)]&2){if(y*(s+1)+x==(s+1)*(s+1))return 1;p.push(y*(s+1)+x)}}function f(){c[c.fy]="#555";c[c.fc](-50,-50,1E5,1E5);c[c.sS]="#000";c[c.ld]=15;c[c.lp]="square";for(i=0;i<(s+1)*(s+1);i++) x-s+y==s&&(c[c.lp]=c[c.li]="round"),c.stroke(new Path2D("M"+30*x+w+30*y+(l[i]&1?"h 30":w)+"M"+30*x+w+30*y+(l[i]&2?"v 30":w)));o="";for(i=0;i<p.length;i++)y=~~(p[i]/(s+1)),x=p[i]%(s+1),o+=" L "+30*x+w+30*y;c[c.sS]="#fff";c.stroke(new Path2D("M0 0 "+o));c[c.ld]=50;c.stroke(new Path2D("M0 0Z"))}function u(e){s=3*min(e,~~(a.height/100));l=[];for(i=0;i<(s+1)*(s+1);i++) l[i]=0,y%3||(l[i]|=1),x%3||(l[i]|=2),l[i]&1&&1==x%3&&(l[i]=.5<random()?0:1),l[i]&2&&1==y%3&&(l[i]=.5<random()?0:2),x==s&&(l[i]&=2),y==s&&(l[i]&=1),x-s+y==s&&(l[i]=1);p=[t=0];r=[0];for(v=[];0<r.length&&!(i=r.shift(),0>vy=~~(i/(s+1)),x=i%(s+1), .indexOf(i)&&(v.push(i), l[i]&1&&r.push(i+1),l[i]&2&&r.push(i+(s+1)),l[i-1]&1&&r.push(i-1),l[i-(s+1)]&2&&r.push(i-(s+1)),t=x-s+y==s)););f();t?b.onkeydown=function(g){switch(g.keyCode%4){case 0:return d(0,-1)&&u(++e),f();case 1:return d(-1,0)&&u(++e),f();case 2:return d(0,1)&&u(++e),f();case 3:return d(1,0)&&u(++e),f()}}:setTimeout(function(){u(e)},0)}c[c.ta](0,a.height);c.scale(1,-1);c[c.ta](50,50);w=" ";u(1);
```

Although it is very hard to read, I did notice that there are multiple `.indexOf` methods that are apparently missing the object they are called on.

It seems to me that this is a problem with the packing algorithm. Can someone shine light on this problem and hopefully fix it?

**Comment by Qqwy** [comment] 2016-02-07 10:31
The exact settings I used (although RegPack still returns malformed code with other settings, including the default ones) are:

-Attempt method hashing and renaming for 2D context only
-Don't reassign variable names to produce consecutive blocks
-Encapsulate with Math

**Comment by Siorki** [comment] 2016-02-07 22:35
I was able to pack your code with both FF and Chrome, put it back into the shim and have it work properly. 

The preprocessed code is 1503b long : 
```javascript
for(i in c)c[i[0]+i[6]]=i;function d(e,g){0!=e&&(g=0);y=~~(p[p.length-1]/(s+1))+g;x=p[p.length-1]%(s+1)+e;if(0<=p.indexOf(y*(s+1)+x))p.indexOf(y*(s+1)+x)==p.length-2&&p.pop();else if(e&&l[min(y*(s+1)+x,y*(s+1)+(x-e))]&1||g&&l[min(y*(s+1)+x,(y-g)*(s+1)+x)]&2){if(y*(s+1)+x==(s+1)*(s+1))return 1;p.push(y*(s+1)+x)}}function f(){c[c.fy]="#555";c[c.fc](-50,-50,1E5,1E5);c[c.sS]="#000";c[c.ld]=15;c[c.lp]="square";for(i=0;i<(s+1)*(s+1);i++)y=~~(i/(s+1)),x=i%(s+1),x-s+y==s&&(c[c.lp]=c[c.li]="round"),c.stroke(new Path2D("M"+30*x+w+30*y+(l[i]&1?"h 30":w)+"M"+30*x+w+30*y+(l[i]&2?"v 30":w)));o="";for(i=0;i<p.length;i++)y=~~(p[i]/(s+1)),x=p[i]%(s+1),o+=" L "+30*x+w+30*y;c[c.sS]="#fff";c.stroke(new Path2D("M0 0 "+o));c[c.ld]=50;c.stroke(new Path2D("M0 0Z"))}function u(e){s=3*min(e,~~(a.height/100));l=[];for(i=0;i<(s+1)*(s+1);i++)y=~~(i/(s+1)),x=i%(s+1),l[i]=0,y%3||(l[i]|=1),x%3||(l[i]|=2),l[i]&1&&1==x%3&&(l[i]=.5<random()?0:1),l[i]&2&&1==y%3&&(l[i]=.5<random()?0:2),x==s&&(l[i]&=2),y==s&&(l[i]&=1),x-s+y==s&&(l[i]=1);p=[t=0];r=[0];for(v=[];0<r.length&&!(i=r.shift(),0>v.indexOf(i)&&(v.push(i),y=~~(i/(s+1)),x=i%(s+1),l[i]&1&&r.push(i+1),l[i]&2&&r.push(i+(s+1)),l[i-1]&1&&r.push(i-1),l[i-(s+1)]&2&&r.push(i-(s+1)),t=x-s+y==s)););f();t?b.onkeydown=function(g){switch(g.keyCode%4){case 0:return d(0,-1)&&u(++e),f();case 1:return d(-1,0)&&u(++e),f();case 2:return d(0,1)&&u(++e),f();case 3:return d(1,0)&&u(++e),f()}}:setTimeout(function(){u(e)},0)}c[c.ta](0,a.height);c.scale(1,-1);c[c.ta](50,50);w=" ";u(1);
```

Crushed output clocks at 1000b : 
```javascript
_='i in c)c[0]+i[6]@i;X d,g0!=eB(g=0G9/z)+g;x=%z+e;if(0<=pIU))pIU)pR-2Bp.pop(Gelse ify+(x-e))]&1||g(y-g)+x)]&2ifUz)1;p8U)}}X f(Yfy@"#555";Yfc](-5-51E5,1E5G000";d@15;p@"square"^7Jp@i@"round"KjQ+($1?"h+"MQ+($2?"v)Go=""ApR9p]p]%z,o+=" L Q;fff"	 "+o)Gd@50	Z"))}X us=3*min,~~(/100)Gl=[]^`=y1Kx2K$1B1xN1K$2B1yN2KxJ$=2KyJ$=1K7J`=1Gp=[t=0];r=[0];v=[];0<rRB!(i=r.shift(K0>vI(i)B(v8(iKH$1W+1K$2W+zKl]&1WKl-z]&2W-zKt=7s)GGf(Gt?b.onkeydown=X(gswitch(g.keyCode%4F0V1V,02V13V1,0_}}:setTimeout(X(u)},0)}Gc.scale(1,G550Gw=" ";u(1Gz(s+1)jc.stroke(new Path2D("M`l]_)Bu(++eKf()^AzHYc[c.XfunctionWBr8(iV:d(U(y+xR.lengthQ"+30*x+w+30*yN%3B(`=.5<random()?0:K),JsB(I.indexOfH9ii%z,G);Fcase B&&A;i=0;i<@]=9y=~~(8.push7x-s+y$`&a.height%3||(`|=Bl[minU,){-10,for(return  30":w)[i==YsS@"#p[pR](eYl*z_;F;i++)Yta](/zKx=	;j0 0';for(i in g='	$789@ABFGHIJKNQRUVWXY^_`jz')with(_.split(g[i]))_=join(pop());with(Math)eval(_)
```

And the final output is reduced to 980b : 
```javascript
for(_='c.stroke(new Path2D("MB;B0 0A),@(s+1)9/9@x=8c[c.77ta](Y;i++)Xcase W&&V);U)Vu(++e@f(UWK*9J7lI(eH-1G.lengthFp[pFG]]=7sS"#==[i 30":w)return for(0,){(yJ+xVl[min,l]%3||(|=a.height&x-s+y.pushy=~~(;i=0;i<i8i%9,	.indexOfsV(%3V(=.5<random()?0:"+30*x+w+30*y:d(Vr(ifunction9JX	i in c)c[0]+i[6]i; dH,g0!=eV(g=0U/9)+g;x=%9+e;if(0<=p))p)pF-2Vp.pop(Uelse ifHyJ+(x-e))]&1||g(y-g)J+x)]&2if9J)1;p)}} f(7fy"#555";7fc](-5-51E5,1E5U000";Id15;Ip"square"IpIi"round"@B+(1?"h+"M+(2?"v)Uo=""pFXp]8p]%9,o+=" L ;fff"A "+o)UId50AZ"))} uHs=3*minH,~~(/100)Ul=[]=y1@x2@1V1x1@2V1y2@x=2@y=1@=1Up=[t=0];r=[0];v=[];0<rFV!(i=r.shift(@0>v(i)V(v(i@	1+1@2+9@lG]&1G@l-9]&2-9@t=s)UUf(Ut?b.onkeydown=(gswitch(g.keyCode%4W0GK1G,0K21K31,0)Vu(++e@f()}}:setTimeout((uH)},0)}YUc.scale(1,GUY550Uw=" ";u(1U';g=/[-F-KU-Y7-9@-B]/.exec(_);)with(_.split(g))_=join(shift());with(Math)eval(_)
```
This is identical to the packed code you posted, except maybe for the control characters which github converted all to '?'

Comparing your expansion of the variable _ to the preprocessed code shows a few expressions in the wrong order, as if characters 8 and 9 had been mixed up in the packed code.

Can you please tell me :
 - which browser/OS are you using ?
 - do the results you obtain from the preprocessing and crush phase match those above ?
 - do they work properly when put into the shim ?

Last, but unrelated point : option `with(Math)` does not make your code shorter (980b with it, 980b without). I suggest you drop it as it will make your code run slower.

**Comment by Qqwy** [comment] 2016-02-08 09:11
- I am using Linux (Mint, 17.2) and I obtain above results running both Chromium 47.0.2526.73 and Firefox  43.0 .

- The preprocessed code matches 1:1. It works, as long as `encapsulate with math` is unchecked (as the `Math.` statements will be removed but encapsulation cannot be done in this step)

-  The crushed code matches 1:1, (as far as can be seen without checking the control characters)

The crushed code does *not* work. (Regardless of the `encapsulate with Math` setting).
Logging `_` before eval'ing shows:

    for(i0in0c)c[i[0]+i[6]]=i;function0d(e,g){0!=e&&(g=0);y=~~(p[p.length-1]/(s+1))+g;x=p[p.length-1]%(s+1)+e;if(0<=p.indexOf(y*(s+1)+x))p.indexOf(y*(s+1)+x)==p.length-2&&p.pop();else0if(e&&l[min(y*(s+1)+x,y*(s+1)+(x-e))]&1||g&&l[min(y*(s+1)+x,(y-g)*(s+1)+x)]&2){if(y*(s+1)+x==(s+1)*(s+1))return01;p.push(y*(s+1)+x)}}function0f(){c[c.fy]="#555";c[c.fc](-50,-50,1E5,1E5);c[c.sS]="#000";c[c.ld]=15;c[c.lp]="square";for(i=0;i<(s+1)*(s+1);i++)y=~~(i/(s+1)),x=0;c.stroke(new0Path2D("M0i%(s+1),x-s+y==s&&(c[c.lp]=c[c.li]="round"),c.stroke(new0Path2D("M"+30*x+w+30*y+(l[i]&1?"h030":w)+"M"+30*x+w+30*y+(l[i]&2?"v030":w)));o="";for(i=0;i<p.length;i++)y=~~(p[i]/(s+1)),x=0;c.stroke(new0Path2D("M0p[i]%(s+1),o+="0L0"+30*x+w+30*y;c[c.sS]="#fff"00"+o));c[c.ld]=500Z"))}function0u(e){s=3*min(e,~~(a.height/100));l=[];for(i=0;i<(s+1)*(s+1);i++)y=~~(i/(s+1)),x=0;c.stroke(new0Path2D("M0i%(s+1),l[i]=0,y%3||(l[i]|=1),x%3||(l[i]|=2),l[i]&1&&1==x%3&&(l[i]=.5<random()?0:1),l[i]&2&&1==y%3&&(l[i]=.5<random()?0:2),x==s&&(l[i]&=2),y==s&&(l[i]&=1),x-s+y==s&&(l[i]=1);p=[t=0];r=[0];for(v=[];0<r.length&&!(i=r.shift(),0>v.indexOf(i)&&(v.push(i),y=~~(i/(s+1)),x=0;c.stroke(new0Path2D("M0i%(s+1),l[i]&1&&r.push(i+1),l[i]&2&&r.push(i+(s+1)),l[i-1]&1&&r.push(i-1),l[i-(s+1)]&2&&r.push(i-(s+1)),t=x-s+y==s)););f();t?b.onkeydown=function(g){switch(g.keyCode%4){case00:return0d(0,-1)&&u(++e),f();case01:return0d(-1,0)&&u(++e),f();case02:return0d(0,1)&&u(++e),f();case03:return0d(1,0)&&u(++e),f()}}:setTimeout(function(){u(e)},0)}c[c.ta](0,a.height);c.scale(1,-1);c[c.ta](50,50);w="0";u(1);


As can be seen, something clearly is going wrong here. It seems that certain(all?) whitespace has been replaced by `0`'s. [Here they are side-by-side](https://gist.github.com/Qqwy/ae4c2b593aefb1fc1ce6)

- For whatever reason, the unpacking of the `crush` step is very different from the unpacking of the `RegPack` step. (although both contain errors, with the errors in the latter step possibly propagating from the first)

**Comment by homecoded** [comment] 2016-02-08 09:54
Not sure if this is of any help: I cannot reproduce the problems on Ubuntu 14.04 with Chrome Version 48.0.2564.97 (64-bit). The packing works just fine. I don't see any of the white-space issues. 

Apparently, it's not a (general) Linux issue.

**Comment by Siorki** [comment] 2016-02-08 22:21
I surmise that the copy-paste operation between your browser and text editor might be altering the contents, especially as far as control characters are concerned.

To check that hypothesis, could you please try the following operations : 
 - first, copy here the contents of the info box next to the crush phase (the one listing the tokens and replaced strings)
 - then, try to pack your code using the original [jscrush](http://www.iteral.com/jscrush/) and check whether the result works in the shim or not
 - third, get the base64 output from RegPack (free of control characters), copy it to the shim and try to run it from there : ``eval(atob(base64Code))``
 - last, try another text editor to see if it works around your issue.

**Comment by Siorki** [comment] 2016-02-16 21:56
Any update regarding this issue ? I'd linke to include it in 4.0.1 if it can be solved in time.

**Comment by Siorki** [comment] 2016-02-27 18:40
Lack of recent updates => postponed to next version

**Comment by jamesseanwright** [comment] 2016-03-05 18:20
I was experiencing similar issues; your suggestion of invoking `eval(atob(base64Code))` works. Personally, I think Sublime is converting some of the characters upon pasting.

Thanks so much for this project by the way. Seriously, it's very impressive!

**Comment by jamesseanwright** [comment] 2016-03-05 19:15
Just tried pasting RegPack's output into Visual Studio Code and it works. I tried various encoding settings in Sublime to no avail.

**Comment by Siorki** [comment] 2016-03-11 20:15
Great, thank you for sharing that. I might start mentioning incompatible text editors.

**Comment by Qqwy** [comment] 2016-03-15 07:53
Thank you very much for your work, @jamesseanwright  and @Siorki . Sorry that I was unable to respond earlier; In the end I missed the deadline for the JS1k because of work.

Very interesting to see that Sublime seems to not support some of the characters. I will test this myself and report back with my findings as well.

**Comment by Siorki** [comment] 2017-01-29 19:57
With no further news, closing this issue as won't fix.

**Closed** 2017-01-29 19:57 UTC
Labels: wontfix
